### ISSUE TITLE
Game does not boot, stuk on blue screen

### ISSUE THREAD

**Issue by worldsiko** [Tankken/Bugs#15] opened 2021-07-06 19:19 UTC
Tankista does not come further than a blue screen on startup, both on admin and standard mode.
I have to force close it via task manager, via the windows task bar nothing happens or it takes a very long [time]
![Tankista-Windows_XWS91h4vRc](https://user-images.githubusercontent.com/53947826/124655254-e6e70c00-de9f-11eb-8777-7293fb72f6f1.png)

**Comment by Ravbug** [comment] 2021-08-09 07:06
I have not been able to reproduce this, have you tried deleting your settings file and relaunching the game? 
The settings file on Windows is located in `\Users\<your user>\AppData\LocalLow\RRSoftware\Tankista Alpha\settings.json`.

**Comment by worldsiko** [comment] 2021-08-12 11:03
Removing the settings file and relaunching the game doesn't seem to have fixed it for me on 0.0.4 and the problem still seems to be occuring on the 0.0.5 release for me, just only a blue screen, i've tried relaunching the game by removing the settings file again, but nothing seems to work. Also running the game in admin mode doesn't seem to have made a difference. Changing the compatibility mode from Windows 8-Vista also didn't seem to make a difference. Maybe my computer specifications have to do something with this? I am very unsure.
![Tankista-Windows_c4MwgzCdux](https://user-images.githubusercontent.com/53947826/129186103-1a8886fd-0b24-467c-8e95-c09d33ee235c.png)

**Comment by Ravbug** [comment] 2021-08-13 07:04
Can you try editing `settings.json` to force the game into windowed mode? You can do this by changing `"fullscreen": true` to `"fullscreen": false`

Also check underneath it what the values for `displayWidth` and `displayHeight` are.

**Comment by Ravbug** [comment] 2021-08-13 23:13
> You can do this by changing "fullscreen": true to "fullscreen": false

This turns out to be the fix, so I am closing the issue. If anyone else has this issue, try disabling fullscreen via the settings file as described above.

**Closed as completed by Ravbug** 2021-08-13 23:13 UTC
Labels: bad behavior, visual glitch, Resolved, ui problem, cannot reproduce, hang
