### ISSUE TITLE
DualShock4 Controller not bound correctly

### ISSUE THREAD

**Issue by grsan45** [Tankken/Bugs#8] opened 2020-11-14 07:39 UTC
**Describe the bug**
Cannot use dualshock4 controller for in-game actions, even if bound when joining

**To Reproduce**
1. Join game with DS4 controller using L1+R1

**Expected behavior**
For controller to be set as the control method, not Keyboard+Mouse

**Screenshots / Videos**
[player.log](https://hasteb.in/gagexica.makefile)

**System Information:**
 - OS: Windows
 - Game Version 0.0.2

**Comment by Ravbug** [comment] 2021-08-29 18:45
Does this still reproduce on the most recent version?

**Comment by Ravbug** [comment] 2022-04-11 00:04
I borrowed a PlayStation 4 controller to test this and I'm not able to reproduce it on 0.0.6 for either macOS nor Windows. Note that I am not using any third party drivers for this, I just plugged the controller into my computer and used the default driver. 

Does this still happen for you @grsan45 ?

**Comment by Ravbug** [comment] 2022-04-16 18:37
Closing because of inability to reproduce -- if this issue appears in the future, feel free to re-open or submit a new issue.

**Closed as completed by Ravbug** 2022-04-16 18:37 UTC
Labels: bad behavior, cannot reproduce
